name: Pull request build and push

on: pull_request

env:
  DOCKER_IMAGE_NAME: dolittle/scaffolding

jobs:
  pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup dotnet
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: '7.0.x'
          include-prerelease: true
      - name: Install dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build
    #- name: Test with the dotnet CLI
    #  run: dotnet test        

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      #- name: Build
      #  run: go build .

      #- name: Make output dir
      #  working-directory: ${{ env.SOURCE_PATH }}
      #  run: mkdir output

      #- name: Run tests
      #  working-directory: ${{ env.SOURCE_PATH }}
      #  run: |
      #    go test ./... --coverprofile output/test-codecoverage.cov

      #- name: Install Code Climate
      #  working-directory: ${{ env.SOURCE_PATH }}
      #  run: |
      #    curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-0.10.1-linux-amd64 > ./cc-test-reporter
      #    chmod +x ./cc-test-reporter

      #- name: Report code coverage to Code Climate
      #  working-directory: ${{ env.SOURCE_PATH }}
      #  run: |
      #    ./cc-test-reporter format-coverage output/test-codecoverage.cov -t gocov -o output/test-codecoverage-codeclimate.json -p github.com/dolittle/platform-api
      #    CC_TEST_REPORTER_ID=${{ secrets.CC_TEST_REPORTER_ID }} \
      #    GIT_BRANCH=${{ env.GITHUB_REF }} \
      #    GIT_COMMIT=${{ env.GITHUB_SHA }} \
      #    ./cc-test-reporter \
      #    upload-coverage -i output/test-codecoverage-codeclimate.json

      - name: Push PR Docker image
        uses: docker/build-push-action@v2
        with:
          push: true
          context: "."
          file: ./Dockerfile
          # todo: semver
          tags: ${{ env.DOCKER_IMAGE_NAME }}:${{ github.head_ref }}
